
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web


  celery:
    build: .
    command: bash -c "celery -A config worker -l INFO"
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  celery_beat:
    build: .
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - db
      - celery
    env_file:
      - ./.env

  redis:
      image: redis:7
      ports:
        - "6379:6379"
      env_file:
        - ./.env


volumes:
  postgres_data:
  static_volume:
  redis_data:
