
services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume: