# Generated by Django 5.2.4 on 2025-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Флаг приятности",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Переодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_do",
                    models.PositiveIntegerField(
                        blank=True,
                        default=120,
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Публичность"
                    ),
                ),
                (
                    "send_indicator",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Индикатор отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
